add the User controller and view
DumontNicolas/All-a-board pull request #5
Opened 2021-02-15 16:55 UTC by claraHEURTEUX

Cher camarades, 

Pourriez-vous review mon long et fastidieux code concernant la show des users.

2021-02-15 16:57 UTC, jayk-u requested changes
Please check this comment.

2021-02-15 16:57 UTC, jayk-u commented on app/controllers/user_controller.rb
> +    @user = user.find(params[:id])
Il semblerait que ce soit `User.find`, non ?

2021-02-15 16:58 UTC, claraHEURTEUX commented on app/controllers/user_controller.rb
> +    @user = user.find(params[:id])
Oh, bien joué Jay. Tu n'as pas failli au test.

2021-02-15 17:04 UTC, DumontNicolas reviewed
ça m'a l'air pas mal

2021-02-16 09:39 UTC, DumontNicolas approved these changes

2021-02-16 09:39 UTC, merged